site_name: My Docs
theme:
  name: material


site_url: https://runtimevic.github.io/MkDocs_Documentacion/
nav:
    - Home: index.md
    - Article: article.md
    - contacto: contact.md
    - page: page1.md