site_name: My Docs
theme:
  name: material
  palette:
    scheme: slate  

site_url: https://runtimevic.github.io/MkDocs_Documentacion/
nav:
    - Home: index.md
    - Article: article.md
    - contacto: contact.md
    - page1: page1.md
    - page2: page2.md
    - page3: page3.md
    - page4: page4.md
    - OOP: OOP_Curso_Youtube_Runtimevic.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
    