site_name: Programación Orientada a Objetos OOP IEC61131-3 Curso Youtube by Runtimevic
theme:
  name: material
#  logo: imagenes/OOP_Logo2.png
  logo: imagenes/oop_logg.webp
  palette:
     # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#  features:
#    - navigation.tabs        
        
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16    

site_url: https://runtimevic.github.io/OOP-IEC61131-3--Curso-Youtube/

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/v%C3%ADctor-dur%C3%A1n-mu%C3%B1oz-2879a913/
  version:
    provider: mike    

markdown_extensions:
  - attr_list
  - md_in_html  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true      
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde   
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
    - Introduccion: index.md
    - Tipos de paradigmas: tipos de paradigmas.md
    - Clases y Objetos: clases y objetos.md
    - Principios OOP: 
       - 4 Pilares: principios/_principios OOP.md
       - Abstracción: principios/abstraccion.md
       - Encapsulamiento: principios/encapsulamiento.md
       - Herencia: principios/herencia.md
       - Polimorfismo: principios/polimorfismo.md
    - Relaciones: relaciones.md
    - SOLID: 
       - SOLID: solid/_SOLID.md
       - Principio de Responsabilidad Única: solid/Principio de Responsabilidad Única.md
       - Principio de Abierto/Cerrado: solid/Principio de Abierto_Cerrado.md
       - Principio de Sustitución de Liskov: solid/Principio de Sustitución de Liskov.md
       - Principio de Segregación de Interfaz: solid/Principio de Segregación de Interfaz.md
       - Principio de Inversión de Dependencia: solid/Principio de Inversión de Dependencia.md
    - UML: UML.md
    - Patrones de Diseño:
       - Patrones de Diseño : Patrones de Diseño/_Patrones de Diseño.md 
    - Links: links.md 