site_name: Programación Orientada a Objetos OOP IEC61131-3 Curso Youtube by Runtimevic
theme:
  name: material
#  logo: imagenes/OOP_Logo2.png
  logo: imagenes/oop_logg.webp
  palette:
     # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#  features:
#    - navigation.tabs        
        
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16    

site_url: https://runtimevic.github.io/OOP-IEC61131-3--Curso-Youtube/

nav:
    - Introduccion: index.md
    - Tipos de paradigmas: tipos de paradigmas.md
    - Clases y Objetos: clases y objetos.md
    - Principios OOP: 
       - 4 Pilares: principios/principios OOP.md
       - Abstracción: principios/abstraccion.md
       - Encapsulamiento: principios/encapsulamiento.md
       - Herencia: principios/herencia.md
       - Polimorfismo: principios/polimorfismo.md
    - Relaciones: relaciones.md
    - SOLID: SOLID.md

    - Home: index.md
    - Getting Started:
            - Introduction:     GettingStarted/Introduction.md
            - First Steps:      GettingStarted/GettingStarted.md
            - Quick Tips:       GettingStarted/QuickTips.md
    - Code Reference:
        - Overview:             CodeReference/Objectives.md
        - Objects:
            - Mover:                CodeReference/Mover.md
            - Mover List:           CodeReference/MoverList.md
            - Position Trigger:     CodeReference/PositionTrigger.md
            - Speed Trigger:        CodeReference/SpeedTrigger.md
            - Station:              CodeReference/Station.md
            - Zone:                 CodeReference/Zone.md
        - Diagnostics:
            - Basics:           CodeReference/Diagnostics.md
            - ErrorMovers:      CodeReference/ErrorMovers.md
            - Event Logger:     CodeReference/EventLogger.md
            - Utility Library:  CodeReference/UtilityLibrary.md
    - Examples:
        - Station to Station:   Examples/StationRouting.md
  

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/v%C3%ADctor-dur%C3%A1n-mu%C3%B1oz-2879a913/
  version:
    provider: mike    

markdown_extensions:
  - attr_list
  - md_in_html  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde   
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - admonition   